### PR TITLE
Fix for parsing type strings for tuples containing static arrays of tuples

### LINKED ISSUE #12: Cannot parse type strings for tuples containing static arrays of tuples
## Problem

Currently this repo fails to parse types like this: `(bool,bool,(string,uint64)[3])`.

It appears that having a static array of tuples (`(string,uint64)[3]`) inside of a tuple causes an unexpected failure to parse.

I've done some investigation and I believe the bug is in the `parseTupleContent` function.

## Potential Solutions
After some investigation, it appears that the JS and Python SDKs are not affected by this bug, so perhaps we can look at their implementations to see how they handle this case.

### PR DESCRIPTION
**Pull request by ahangsu**
Fix #12

### CODE REVIEW

**Comment by ahangsu** [comment]
seems that the CI codecov-upload is having some issue: https://github.com/codecov/codecov-action/issues/598

File: abi/type.go [hunk 1]
```diff
@@ -186,8 +186,10 @@ type segment struct{ left, right int }
 // parseTupleContent splits an ABI encoded string for tuple type into multiple sub-strings.
 // Each sub-string represents a content type of the tuple type.
 // The argument str is the content between parentheses of tuple, i.e.
+//
 // (...... str ......)
-//  ^               ^
+//
+//	^               ^
```
Comment (bbroder-algo) [inline abi/type.go:192]: probably don't want this

Comment (ahangsu) [reply abi/type.go:192]: 👍 I think it is because of go 1.19 formatter. I will leave a TODO here to revert the formatter change.

File: abi/type.go [hunk 2]
```diff
@@ -186,8 +186,10 @@ type segment struct{ left, right int }
 // parseTupleContent splits an ABI encoded string for tuple type into multiple sub-strings.
 // Each sub-string represents a content type of the tuple type.
 // The argument str is the content between parentheses of tuple, i.e.
+//
```
Comment (ahangsu) [inline abi/type.go:189]:
```suggestion
```

File: abi/type.go (hunk 1 above)
Comment (ahangsu) [inline abi/type.go:192]:
```suggestion
//	^               ^
```

File: abi/type.go [hunk 3]
```diff
@@ -226,6 +232,12 @@ func parseTupleContent(str string) ([]string, error) {
 			leftParenIndex := stack[len(stack)-1]
 			stack = stack[:len(stack)-1]
 			if len(stack) == 0 {
+				// increase index til it meets comma, or end of string
+				forwardIndex := index + 1
+				for forwardIndex < len(str) && str[forwardIndex] != ',' {
+					forwardIndex++
+				}
+				index = forwardIndex - 1
```
Comment (bbroder-algo) [inline abi/type.go:239]: looks good to me

File: abi/type_test.go [hunk 4]
```diff
@@ -505,6 +601,17 @@ func TestTypeMISC(t *testing.T) {
...
 	}
+	// add testcase for array of tuples into testpool
+	testpoolTupleArray := make([]Type, 0, 200)
+	for i := 0; i < 100; i++ {
+		testpoolTupleArray = append(testpoolTupleArray, makeDynamicArrayType(testpoolTuple[i]))
+	}
+	for i := 0; i < 100; i++ {
+		testpoolTupleArray = append(testpoolTupleArray, makeStaticArrayType(testpoolTuple[i], 10))
+	}
+	for i := 0; i < 100; i++ {
```
Comment (bbroder-algo) [inline abi/type_test.go:612]: should this be 200?

File: abi/type.go [hunk 5]
```diff
@@ -212,11 +214,15 @@ func parseTupleContent(str string) ([]string, error) {
 	var stack []int
```
Comment (bbroder-algo) [inline abi/type.go:213]: line 203 above, error should be "parsing error: tuple content should not start or end with comma"
also typo in comment noe = not

File: abi/type_test.go (hunk 4 above)
Comment (ahangsu) [reply abi/type_test.go:612]: this can be any number: I am here sampling 100 tuple types from
- types in `testpool`
- types in `testpoolTupleArray` (which has length 200)

File: abi/type.go (hunk 5 above)
Comment (ahangsu) [reply abi/type.go:213]: 👍 good find, will change accordingly.

File: abi/type_test.go (hunk 4 above)
Comment (bbroder-algo) [reply abi/type_test.go:612]: oh I see, it just gets appended below.

File: abi/type_test.go [hunk 6]
```diff
@@ -520,6 +627,14 @@ func TestTypeMISC(t *testing.T) {
 	}
 
 	testpool = append(testpool, testpoolTuple...)
+	testpool = append(testpool, testpoolTupleArray...)
+	for _, testcase := range testpool {
+		deseralized, err := TypeOf(testcase.String())
```
Comment (algochoi) [inline abi/type_test.go:632]:
```suggestion
		deserialized, err := TypeOf(testcase.String())
```

**Review by algochoi — COMMENTED** [review]
Looks good 👍

File: abi/type_test.go (hunk 6 above)
Comment (ahangsu) [reply abi/type_test.go]: 👍

**Review by bbroder-algo — APPROVED** [review]
